name: aradia
description:
  "A Flutter app that provides access to a wide range of audiobooks from Librivox.
  Users can browse and listen to audiobooks in various genres, with the ability to
  customize their listening experience through a built-in audio player. The app
  features a modern interface with a focus on ease of use, allowing users to
  seamlessly explore and enjoy classic literature in audio format."

publish_to: "none"

version: 2.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  fpdart: ^1.1.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  go_router: ^14.6.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  audio_service: ^0.18.15
  transparent_image: ^2.0.1
  just_audio: ^0.9.42
  audio_video_progress_bar: ^2.0.3
  rxdart_ext: ^0.3.0
  just_audio_background: ^0.0.1-beta.13
  provider: ^6.1.2
  we_slide: ^2.4.0
  permission_handler: ^11.3.1
  background_downloader: ^8.8.0
  media_store_plus: ^0.1.3
  intl: ^0.19.0
  url_launcher: ^6.3.1
  device_info_plus: ^11.1.1
  ionicons: ^0.2.2
  flutter_background: ^1.3.0+1
  connectivity_plus: ^6.1.1
  back_button_interceptor: ^8.0.0
  visibility_detector: ^0.4.0+2
  open_file: ^3.5.10
  meta: ^1.16.0
  youtube_explode_dart:
    git:
      url: https://github.com/sheikhhaziq/youtube_explode_dart.git
  file_picker: ^10.1.4
  path: ^1.9.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true